# Generated by Django 5.0.1 on 2024-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_alter_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
