# Generated by Django 5.0.1 on 2024-01-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_user_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
