# Generated by Django 5.0.1 on 2024-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=200, null=True, upload_to='images/profile'),
        ),
    ]
